//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerStoreMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTable
    {
        public int Id { get; set; }
        
        [DisplayName("User Name")]
        [Required(ErrorMessage = "Field is required.")]
        public string UserName { get; set; }
        
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Field is required.")]
        public string Password { get; set; }
        
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Field is required.")]
        public string Email { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
